apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/instance: netflix-clone-app
  name: netflix-clone-app-deployment-resource
  #namespace: apps101
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        #image: sevenajay/netflix:latest
        image: rover102/netflix9:latest
        ports:
        - containerPort: 3001   # Use port 3001
